// src/Components/QAComponents/mockQuestions.js
export const mockQuestions = [
  {
    id: 1,
    title: "How to properly handle async/await in React useEffect hook?",
    excerpt:
      "I'm trying to fetch data inside useEffect but getting warnings about cleanup functions. What's the best practice for handling async operations in useEffect?",
    votes: 42,
    answers: 8,
    views: 1523,
    tags: ["reactjs", "async-await", "hooks"],
    author: "Sarah Chen",
    avatar: "SC",
    timeAgo: "5 mins ago",
  },
  {
    id: 2,
    title: "Node.js memory leak detection and prevention strategies",
    excerpt:
      "My Node.js application is consuming more memory over time. What are the best tools and techniques to detect and prevent memory leaks in production?",
    votes: 38,
    answers: 5,
    views: 892,
    tags: ["node.js", "performance", "debugging"],
    author: "Alex Kumar",
    avatar: "AK",
    timeAgo: "12 mins ago",
  },
  {
    id: 3,
    title: "CSS Grid vs Flexbox: When to use which layout system?",
    excerpt:
      "I understand both CSS Grid and Flexbox, but I'm still confused about when to use one over the other. Are there specific use cases where one is clearly better?",
    votes: 67,
    answers: 12,
    views: 2341,
    tags: ["css", "layout", "frontend"],
    author: "Maria Garcia",
    avatar: "MG",
    timeAgo: "23 mins ago",
  },
  {
    id: 4,
    title: "Best practices for JWT token storage in web applications?",
    excerpt:
      "Should I store JWT tokens in localStorage, sessionStorage, or cookies? What are the security implications of each approach?",
    votes: 91,
    answers: 15,
    views: 3876,
    tags: ["security", "jwt", "authentication"],
    author: "David Park",
    avatar: "DP",
    timeAgo: "1 hour ago",
  },
  {
    id: 5,
    title: "How to optimize React app bundle size for production?",
    excerpt:
      "My React app bundle is over 2MB and I need to reduce it. What are the most effective strategies for code splitting and tree shaking?",
    votes: 28,
    answers: 0,
    views: 456,
    tags: ["reactjs", "webpack", "optimization"],
    author: "Lisa Wong",
    avatar: "LW",
    timeAgo: "2 hours ago",
  },
  {
    id: 6,
    title: "PostgreSQL vs MongoDB: Which database for a social media app?",
    excerpt:
      "I'm building a social media platform and need to choose between PostgreSQL and MongoDB. What factors should I consider for scalability and performance?",
    votes: 54,
    answers: 9,
    views: 1678,
    tags: ["database", "postgresql", "mongodb"],
    author: "James Wilson",
    avatar: "JW",
    timeAgo: "3 hours ago",
  },
  {
    id: 7,
    title: "Understanding TypeScript generics with practical examples",
    excerpt:
      "I've read the documentation but still struggling to understand when and how to use TypeScript generics effectively. Can someone explain with real-world examples?",
    votes: 45,
    answers: 7,
    views: 1234,
    tags: ["typescript", "generics", "tutorial"],
    author: "Emily Zhang",
    avatar: "EZ",
    timeAgo: "4 hours ago",
  },
  {
    id: 8,
    title: "Docker multi-stage builds for Node.js applications",
    excerpt:
      "What are the benefits of multi-stage Docker builds and how do I implement them for my Node.js app to reduce image size?",
    votes: 33,
    answers: 4,
    views: 789,
    tags: ["docker", "node.js", "devops"],
    author: "Michael Brown",
    avatar: "MB",
    timeAgo: "5 hours ago",
  },
];
